 # 服务端口
server:
  port: 8301
  #服务名
spring:
  application:
    name: service-vod
    #数据库来连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_vod?characterEncoding=utf-8&&useSSL=false
    username: root
    password: 1025
    #返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #环境配置
    profiles:
      active:dev
  #mybatis日志


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
